config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  devise_for :admins
  root to: "home#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="admin-control">
  <% if admin_signed_in? %>
    <%= link_to 'New Blog', new_blog_path %>
    </br>
    <%= link_to 'Sign out', :destroy_admin_session, :method => :delete %>
  <% end %>
</div>
<div class="blog-home">
  <div class="blog-head data-stellar-background-ratio=" 0.5 "">
    <%= link_to(:root) do %>
      <p>BACK TO WILLYNOGS.COM</p>
    <% end %>
    <h1>Nog Blog</h1>
  </div>

  <div class="fixed-width">
    <div class="ui link cards">
      <% @blogs.each do |blog| %>
        <div class="ui card">
          <%= link_to image_tag(blog.image), blog, :class => "image" %>
          <div class="content">
            <%= link_to blog.title, blog, :class => "header no-link-style" %>
            <div class="meta">
              <span class="date"><%= blog.created_at.strftime('%B %d, %G') %></span>
            </div>
            <div class="description">
              <%= blog.content.truncate_words(20) %>
            </div>
            <div class="post-controls">
              <% if admin_signed_in? %>
                <%= link_to 'Show', blog %>
                <%= link_to 'Edit', edit_blog_path(blog) %>
                <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="footer">
      <p>2016 Will Naugle</p>
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="back-button shake-horizontal">  
  <%= link_to(:blogs) do %>
    <%= fa_icon "arrow-left 2x" %>
    <h3>BACK</h3>
  <% end %>
</div>
<div class="fixed-width">
  <div class="post-header">
    <h1><%= @blog.title %></h1>
  </div>
</div>
  <div class="post-content">
    <%= @blog.content %>
  </div>

app/views/home/index.html.erb
<div class="container">
  <div class="head data-stellar-background-ratio=" 0.5 "">
    <%= link_to(:blogs) do %>
      <p>BLOG</p>
    <% end %>
    <a href="mailto:willynogs@gmail.com"><%= fa_icon "envelope 3x" %></a>
    <a href="http://linkedin.com/in/willnaugle" target="_blank"><%= fa_icon "linkedin-square 3x" %></a>
    <a href="https://github.com/willynogs" target="_blank"><%= fa_icon "github-square 3x" %></a>
    <h1>Will Naugle</h1>
  </div>
</div>
<div class="fixed-width">
  <div class="about">
    <h2>About:</h2>
    <p>I am a third year student at The Ohio State University. I am studying German and Computer & Information Science. Currently I am a Student Web Developer for the university. In the summer of 2015 I spent ten weeks in Dresden, Germany studying German language and culture. My main interests are in web and ios development. If you have any questions or inquiries feel free to email me!</p>
  </div>
  <div class="skills">
    <h2>Skills:</h2>
      <p>I am always working towards becoming a better developer, however, my current skills include:</p>
      <ul>
        <li>HTML</li>
        <li>CSS</li>
        <li>Javascript (jQuery)</li>
        <li>Ruby on Rails</li>
        <li>Swift</li>
      </ul>
  </div>
  <div class="portfolio">
      <h2>Portfolio:</h2>
      <div class="ui link cards">
        
        <div class="ui card">
          <a class="image" href="https://kanye-today.herokuapp.com/">
            <%= image_tag("kanye-today.png") %>
          </a>
          <div class="content">
            <a class="header no-link-style" href="https://kanye-today.herokuapp.com/">Kanye Today</a>
            <div class="meta">
              <span class="date">Ruby on Rails/Twitter API</span>
            </div>
            <div class="description">
              Using the Twitter API and Ruby on Rails I created a web app that collects Kanye West's tweets and analyzes them.
            </div>
          </div>
          <div class="extra content">
            <a class="no-link-style" target="_blank" href="https://github.com/willynogs/Kanye-Today">View Github repo</a>
          </div>
        </div>
        
        <div class="ui card">
          <a class="image" href="http://willynogs.com">
            <%= image_tag("trees.jpeg") %>
          </a>
          <div class="content">
            <a class="header no-link-style" href="http://willynogs.com">Personal Website</a>
            <div class="meta">
              <span class="date">HTML/CSS/Javascript</span>
            </div>
            <div class="description">
              I created this website with my own original HTML and CSS. I then implemented <a target="_blank" href="http://markdalgleish.com/projects/stellar.js/">Stellar.js</a> for a parallax scrolling effect, and <a target="_blank" href="http://semantic-ui.com/views/card.html">Semantic UI</a> for the portfolio cards. I moved this project to rails in order to create a <%= link_to 'blog', :blogs %>.
            </div>
          </div>
          <div class="extra content">
            <a class="no-link-style" target="_blank" href="https://github.com/willynogs/willynogs.github.io">View Github repo</a>
          </div>
        </div>

        <div class="ui card">
          <a class="image" href="https://osuitsm.service-now.com/selfservice/">
            <%= image_tag("service_now.png") %>
          </a>
          <div class="content">
            <a class="header no-link-style" href="http://willynogs.com">Ohio State ServiceNow</a>
            <div class="meta">
              <span class="date">HTML/CSS/Javascript</span>
            </div>
            <div class="description">
              I currently work as a Student Devloper for Ohio State's OCIO. I work on the ServiceNow team helping to manage our instance of the ServiceNow platform. This position includes working with CSS, HTML, Angular, Rails, working in an Agile enviroment, as well as many other things.
            </div>
          </div>
          <div class="extra content">
            See examples (currently empty)
          </div>
        </div>

        <div class="ui card">
          <a class="image" target="_blank" href="https://desolate-basin-2060.herokuapp.com/">
            <%= image_tag("twitter.png") %>
          </a>
          <div class="content">
            <a class="header no-link-style" target="_blank" href="https://desolate-basin-2060.herokuapp.com/">Twitter Clone</a>
            <div class="meta">
              <span class="date">Ruby on Rails</span>
            </div>
            <div class="description">
              This is a Twitter clone I created by following Michael Hartl's <a target="_blank" href="https://www.railstutorial.org/">Rails Tutorial</a>. This project utilizes Bootstrap and is hosted on Heroku.
            </div>
          </div>
          <div class="extra content">
            <a class="no-link-style" target="_blank" href="https://github.com/willynogs/rails_tutorial">View Github repo</a>
          </div>
        </div>
        <div class="ui card">
          <a class="image" target="_blank" href="realfriends.html">
            <%= image_tag("boyz.jpg") %>
          </a>
          <div class="content">
            <a class="header no-link-style" target="_blank" href="realfriends.html">THREE.js Experiment</a>
            <div class="meta">
              <span class="date">THREE.js</span>
            </div>
            <div class="description">
              This is just an experiment with THREE.js.
            </div>
          </div>
          <div class="extra content">
            <a class="no-link-style" target="_blank" href="https://github.com/willynogs/willynogs.github.io">View Github repo</a>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <p>2016 Will Naugle</p>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WN</title>
  <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'csshake-horizontal.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'card.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>